### ISSUE TITLE
simplify faction loadout generation

### ISSUE THREAD

**Issue by milivojm** [CntoDev/template#8] opened 2016-03-30 07:43 UTC
Mission makers tend to create custom loadout and custom factions for specialized missions. Our goal should be to simplify the process as much as we can, make it simple and fast to use.
1. Should we go the 'F3 way', use defines in the beginning to change the gear while having a scripted skeleton below. 
2. Should we give them only small changes to the default gear with functions that basically just replace item X with item Y, uniform X with uniform Y? 
3. Should we use faction prototype unit with transformation functions for others? For example, MM creates a one unit and gives it a variable name in .sqm and calls a certain function which states _this is faction prototype, use it's gear by default_. All spawned units then 'inherit' it's gear but also apply some custom transformation based on the class name. Custom transformations are looked for in some folder in the mission. 
4. Something else.

**Comment by freghar** [comment] 2016-03-30 08:23
I like the faction prototype / hierarchy idea, but we could do it even without extra template defines.

We could, based on some identifier, use a hierarchy tree of Arsenal-based loadouts - ie. the base unit would define uniform, helmet, vest, radios, bandages, etc. and "on top of that" there would be soldiers with just weapons, magazines, grenades, etc., .. and on top of that, soldiers with just nightvision.

The result would be a "stacked" soldier of all these, conflicts (not enough space, etc.) would be ignored - it would depend on how scripting commands behave in these situations as I don't think we can even detect "not enough space" conditions.

All that would be optional, though - one could still define everything in single-Arsenal-ized soldier entities. The system would be also quite CPU-expensive and potentially take some time to "load", but moving it to text define files wouldn't help.
We would also need to keep the stacked soldiers "around" for JIP players, who wouldn't have their loadout saved.

Overall, I still think the original Arsenal copy/paste is a much safer and more viable option (as the engine loads most of it on initial spawn + JIP), possibly with (2), as you mentioned. :(

**Comment by milivojm** [comment] 2016-03-30 10:54
I like the idea. Basically, we would mimic 'inheritance' in a object oriented way. How would MM use this? By setting init field in the mission template or would we override onPlayerRespawn (forcing it on initial connect) and there look for things like 'which class does a player belong and what faction'? The later seems more convenient for the MMs. 

Also, we could go on and insert the same function call in curator in `CuratorGroupPlaced` and `CuratorObjectPlaced` event handler.

**Comment by freghar** [comment] 2016-03-30 11:24
Well, we could use the Synchronization mechanic in editor and `synchronizedObjects` to traverse the tree of inheritance. However we would need to mark a starting point and possibly each further "level" (unless we want to make a custom tree walking logic that would detect loops). Even without Synchronization, you would need to do that ie. via some text field or identifier.

That's why, on a second thought, I wouldn't go there. It would involve tons of complex runtime logic (ie. How do you pair the tree to the actual units? Based on `isKindOf`?) and - overall - it just may not be worth it for what it is supposed to do. As @CNTODachi mentioned, just doing the manual Arsenal thing isn't that awful - yes, it's 1-2 minutes of copy&paste tedious work, but creating an inheritance tree and linking it to units could take much more effort for the end user, not mentioning the need to wait during mission start (as we do now) for the logic to settle.

However if you need this functionality for your goals, I'm not against it - I'm just concerned that it may be too overwhelming by being too powerful. :)

Why would we need this for Curator-placed objects again?

**Comment by milivojm** [comment] 2016-03-30 12:25
I was thinking of using `typeOf` and then choosing the arsenal exported loadout by convention (look for file with the same class name). We would provide a skeleton of #include scripts for them and they could just append the grenade here, the backpack there etc, in a way you've described. Or they can just, like you said, export every loadout in it's own file and just name it correctly as the class name. That way init field settings are gone and we could also do the spawn from Zeus feature (see below).

Curator-placed objects if the MM wants to spawn groups from his custom faction. I didn't explain myself very clearly, but sometimes MM wants a custom AI faction too, not just playable. We wanted North Korea style enemies in Blind Obelisk campaign. Of course, that feature would need your _move AI to server_ feature.

**Comment by milivojm** [comment] 2016-03-30 12:31
Eh, yes, that still leaves me with the problem of Eden placed AI units, they would either need to use init field or do something special. Nothing pops up in my mind right now. 

Maybe `RegisteredToWorld3DEN` ?

**Comment by freghar** [comment] 2016-03-30 12:34
Ah, so basically a MM would create per-class Arsenal configs in a directory and these would be automatically loaded whenever the class appears?
- on player
- from editor
- curator-spawned

?

This is a perfect usecase for CBA's XEHs, which you can add to a specific CfgVehicles class (which you can do even vanilla, but not from a mission - XEHs can be added from a mission (description.ext)).

Right, this could work pretty well, but you would still need to somehow handle files not existing in a directory when calling `execVM` or use global variables or ideally `parsingNamespace` to indicate which classes have specified configs.

**Comment by freghar** [comment] 2016-03-30 12:35
> but you would still need to somehow handle files not existing in a directory when calling execVM or use global variables or ideally parsingNamespace to indicate which classes have specified configs.

Actually, scratch that, when you specify the class as a XEH, that should be enough.

**Comment by milivojm** [comment] 2016-03-30 12:38
Yes. I didn't use CBA XEH before, but there is a first time for everything I guess. I will have a look.

**Comment by freghar** [comment] 2016-03-30 12:42
```
class Extended_Init_EventHandlers {
    class B_RangeMaster_F {
        class A3MT_load_gear {
            init = "pls load my gear";
        };
    };
};
```

Should work for any form of initialization from anywhere, even `createVehicle` (script-based spawn).

**Comment by milivojm** [comment] 2016-03-30 12:45
Wow, that's powerful! Thanks!

**Comment by freghar** [comment] 2016-03-30 12:46
Applying it to respawn should be as simple as adding `onRespawn = 1;` below `init =` or so, I don't remember the exact syntax.

**Comment by freghar** [comment] 2016-03-30 12:51
Going into more detail, you could probably use it like

```
class Extended_Init_EventHandlers {
    class B_RangeMaster_F {
        class A3MT_load_gear {
            init = "(_this select 0) call A3MT_fnc_loadGearFile";
            onRespawn = 1;
        };
    };
    class B_Soldier_GL_F : B_RangeMaster_F;
    class B_Soldier_AR_F : B_RangeMaster_F;
    ...
};
```

as you don't need to pass any class-specific arguments. The function can find `typeOf` itself and use that as a filename when loading the loadout.

However I'm not sure if there is a scripting command for loading Arsenal exports.

**Comment by milivojm** [comment] 2016-03-30 13:04
Yes, the this => _this issue with exports. I used to force Chypsa to manually do a replace of this => _this and it is then simple.

**Comment by freghar** [comment] 2016-03-30 13:11
It is a bit confusing, yes,
- `this` is a global variable, set by the engine when processing unit init lines, it works because it does so sequentially
- `_this` is an automatic private variable inside any function (or `{}` block) that contains the passed argument, which often is (but doesn't have to be) an array, hence `(_this select 0)` to get the first member, the init'd unit

**Comment by milivojm** [comment] 2016-03-30 13:14
Interesting. I'm reading CBA [wiki](https://github.com/CBATeam/CBA_A3/wiki/Extended-Event-Handlers-%28new%29) and it says 

> The event handlers are executed for the matching class and all inheriting classes.

Basically, I just need to tie this to the top-most class in the tree and then check for class name in the function. That would save us copy & pasting things.

**Comment by freghar** [comment] 2016-03-30 13:24
Yes, but I'm not sure how you would detect existence of a file, to not throw a script error for classes you don't define loadouts for. If you can solve that during runtime (somehow efficiently as it's going to be executed on any spawn), then great - MM would just need to create the loadout file.

**Comment by milivojm** [comment] 2016-03-31 00:08
I have to say this is working better than expected (great?). I was reluctant to attach the event handler to entire `CAManBase` class hierarchy but performance test on 1000 iterations has given average running time around 1.2 ms for loading a loadout. It works on respawn too. I didn't try to place it with curator though. 

Loadouts are by default placed in the loadouts folder (included in the test mission). Files must be named according to class name they modify.

Test mission is [here](https://drive.google.com/file/d/0B8T9N5ODuzJgMXozcGs4YVF3MUU/view?usp=sharing)

Give it a try and let me know what you think. Also, out of tiredness, I didn't do a pull request as agreed upon (do I need to do it?).

**Comment by freghar** [comment] 2016-03-31 01:19
Feel free to do a pull request next time, it would be a much easier way of commenting on code as I wouldn't have to guess what is added by you and what is just a diff against newer stuff in the repo. You can `git pull --rebase` to get your commits on top of the latest master without a merge commit.

Few comments from what I could see:
- I originally had `description.ext` nested into features, but then found out I cannot re-define `CfgFunctions` multiple times, so I did the `functions.h` thing. As we now need direct `description.txt` access, I would rather have a proper generic `description.ext` nested structure than `extended_handlers.h`. We'll have to check if we can redefine `class Extended_Init_EventHandlers` multiple times and if not, that might be an issue as there's a LOT of similar classes in CBA, not mentioning the inability to use `CAManBase` in any other feature. :(
- Why the `recompile = 1` on functions? It's useful for debugging, but only slows down mission load and unless you modify functions after defining them, it's not needed.
- KK's blog says "EDIT:  No display is available on dedicated to create control so no way of using htmlLoad. Might want to try custom extension if server check is needed." , but editor-spawned units are initially local to the server, aren't they? Does this work for them? Could we perhaps use [exception handling](https://community.bistudio.com/wiki/try) instead?
- I would prefer some convention for storing additional configuration files, not using global variables (`A3MT_loadouts_path`) to define their path. Either directly in `features\Name\`, a specific subfolder (?) or somewhere in mission root. Saves the work of defining potentially multiple variables for multiple features.

**Comment by freghar** [comment] 2016-03-31 01:53
Right, the inability to re-define XEHs anywhere else is an issue. However CBA allows one to add them via functions as well, ie. [addClassEventHandler](http://cbateam.github.io/CBA_A3/docs/files/class_eventhandlers/fnc_addClassEventHandler-sqf.html). If `init.sqf` is too late, a bootstrap function with `preInit = 1` calling this CBA one [should do the trick](https://community.bistudio.com/wiki/Initialization_Order).

**Comment by milivojm** [comment] 2016-03-31 07:41
- `description.ext` - I was trying to avoid having any code regarding this feature in there. I will restructure the code and create a stub `Extended_Init_EventHandlers` and `CAManBase` beneath it, not pretty but will do the trick. 
- `recompile = 1` because Arma doesn't recognize functions in that stage of initialization without it. It simply didn't do anything when recompile = 1 wasn't used. See [link](https://community.bistudio.com/wiki/Initialization_Order).
- I am actually thinking about ditching the `A3MT_fnc_fileExists` logic completely as Arma 3 doesn't break if a file doesn't exist (so it seems). In other words, if there is anything wrong with function called in init event handler, nothing bad will happen.
- there is a major issue with this and I'm afraid I might have to hard-code the path to loadouts. Even though I've created a global, it will not be available on the first run since init is executed way too early for anything setting that global variable. I could try with another function in `preInit` but is that worth the fuss?

**Comment by milivojm** [comment] 2016-03-31 10:30
Ok, have a look at [highway](https://github.com/CntoDev/template/tree/highway) branch. It's untested but that's what I'd do. I wouldn't complicate with init.sqf and new CBA event handlers.

I also removed the `A3MT_fnc_fileExists` as it is a nasty workaround. I have a feeling we can just call `execVM` without worrying if the file exists or not.

**Comment by freghar** [comment] 2016-03-31 11:39
> description.ext - I was trying to avoid having any code regarding this feature in there. I will restructure the code and create a stub Extended_Init_EventHandlers and CAManBase beneath it, not pretty but will do the trick.

As I added in my additional comment, that won't work well with other features, we're better off ditching config-based XEHs and just using the function I linked. The effect should be the same, the XEH config structure is read on runtime anyway (same as the function), not by the engine (like ie. `CfgFunctions`).

> recompile = 1 because Arma doesn't recognize functions in that stage of initialization without it. It simply didn't do anything when recompile = 1 wasn't used. See link.

At which stage? Functions defined in CfgFunctions are compiled as you enter the lobby (or load the mission in editor), way, way before Intialization Order kicks in. Just seems weird to me as I never had to use `recompile = 1` in the final code, whether it was in XEH, unit init lines or even in other `preInit = 1` functions.

> I am actually thinking about ditching the A3MT_fnc_fileExists logic completely as Arma 3 doesn't break if a file doesn't exist (so it seems). In other words, if there is anything wrong with function called in init event handler, nothing bad will happen.

Except people with enabled scripterrors (see a3s launcher options) will see a goatload of spam on the screen (and in rpt log). I really wouldn't just ignore script errors if I were you, but I understand the reasons. Maybe do it only on the server / on `(!hasInterface)`?

> there is a major issue with this and I'm afraid I might have to hard-code the path to loadouts. Even though I've created a global, it will not be available on the first run since init is executed way too early for anything setting that global variable. I could try with another function in preInit but is that worth the fuss?

Well, you could let the user specify a path as a `userconfig.h` define if you want, you can do it like a preprocessor define or via `__EXEC()` and then read it from `parsingNamespace` in the actual sqf code. I wouldn't go there, though, hardcoded paths are fine - is there a good usecase for being able to specify a custom path?

**Comment by freghar** [comment] 2016-03-31 11:53
Also, did you want to push to master? https://github.com/CntoDev/template/commit/f8c10c23c0b0ba5f0fbed33b93aa21d42bbd250e

**Comment by milivojm** [comment] 2016-03-31 12:09
No, I don't want to push to master yet. It's on my branch so I can work wherever I like.

> At which stage? Functions defined in CfgFunctions are compiled as you enter the lobby (or load the mission in editor), way, way before Intialization Order kicks in. Just seems weird to me as I never had to use recompile = 1 in the final code, whether it was in XEH, unit init lines or even in other preInit = 1 functions.

It simply refused to work without it. The second I added `recompile = 1` it started working. It could be a problem with Editor preview. I've tried setting `init = "diag_log _this"` and it worked. Then I've changed it to `init = "_this call A3MT_fnc_loadGearFromFile"` and nothing happened. Tried `init = "(_this select 0) call A3MT_fnc_loadGearFromFile"` and nothing again. Turned on `recompile` and it started working.

> Except people with enabled scripterrors (see a3s launcher options) will see a goatload of spam on the screen (and in rpt log). I really wouldn't just ignore script errors if I were you, but I understand the reasons. Maybe do it only on the server / on (!hasInterface)?

I was running it with scripterrors on. Got no errors on screen nor in .rpt. 

> Well, you could let the user specify a path as a userconfig.h define if you want, you can do it like a preprocessor define or via __EXEC() and then read it from parsingNamespace in the actual sqf code. I wouldn't go there, though, hardcoded paths are fine - is there a good usecase for being able to specify a custom path?

I can't think of one. Unless they want to put something else in loadouts folder really badly.

**Comment by freghar** [comment] 2016-03-31 12:10
I can confirm the following triggered for me in MP,

```
["CAManBase", "init", {systemChat str _this}] call CBA_fnc_addClassEventHandler;
["CAManBase", "respawn", {systemChat str _this}] call CBA_fnc_addClassEventHandler;
```

I wanted to use these as class-ing XEHs is going to be hell if more features use it, as you can't redefine any sub-classes with existing names, imagine:
- feature A wants to hook `CAManBase`
- feature B wants `B_RangeMaster_F`

At this point, it seems reasonable, we could do what you did - put all XEH definitions and sub-classes in a single file (and not an include hierarchy like I imagined) and just `#include` each feature where it needs to be, however what if
- feature C needs to hook 8 different subclasses of `CAManBase`
- feature D needs to reuse 4 of these and hook another 8

it suddenly starts getting really messy as you can't simply define one and inherit remaining 7, because you couldn't `#include` feature C in each. And you can't delegate this to feature C's directory as feature D needs to reuse them.

This was my concern - the class-based approach unfortunately doesn't scale. :(
It works great with addons where you **can** re-define class names, because each "feature" has its own .pbo and that's apparently allowed. Not in a mission, though.

**Comment by freghar** [comment] 2016-03-31 12:12
> No, I don't want to push to master yet. It's on my branch so I can work wherever I like.

Well you did. :) https://github.com/CntoDev/template/commit/f8c10c23c0b0ba5f0fbed33b93aa21d42bbd250e

**Comment by milivojm** [comment] 2016-03-31 12:16
Yup, last night. My error. I'll try to remove that commit from master. If you know how to do it without looking in the manual, please be my guest and write it here. :)

Ok, so you want me to drop the `description.ext` approach altogether. 

I'd then need two event handlers, one for `init` and one for `respawn` basically having the same callback, right? It's just strange that init will work from init.sqf, I have my doubts about it. 

Scratch that, it will work. Like you said - bootstrap function.

**Comment by milivojm** [comment] 2016-03-31 12:21
Eh yes, there is a way but it's not very nice. How about we pretend this didn't happen and I'll overrun it later with quality commit after submitting a pull-request, your review and things will be fine?

```
git reset --hard <old-commit-id>
git push -f <remote-name> <branch-name>
```

Note: As written in comments below, Using this is dangerous in a collaborative environment: you're rewriting history.

**Comment by freghar** [comment] 2016-03-31 12:30
> Yup, last night. My error. I'll try to remove that commit from master. If you know how to do it without looking in the manual, please be my guest and write it here. :)

Sorry, it will forever be there. :) You can push another commit, applying reverse changes,
1. when on a clean working tree (git status shows nothing), `git fetch` and `git checkout origin/master`
2. `git revert f8c10c2`
3. confirm commit message (write & quit editor)
4. `git push origin master`

Force pushing to master is denied by Github (it's considered a "protected branch"). Alternatively, you can just leave it there and base further changes on it (I would recommend that approach instead).

> Ok, so you want me to drop the description.ext approach altogether.

If possible, yes. It would be awesome if we could somehow do this cleanly or hope we won't have such scalability needs, but if we can do (almost) the same thing with CBA functions, ...

Vanilla `Cfg*` structures in `description.ext` are better "scalable" as they (as far as I know) have only one level of unique names (the `CfgFunctions`, `CfgSounds`, etc. itself), anything below it can have an arbitrary name.

> I'd then need two event handlers, one for init and one for respawn basically having the same callback, right? It's just strange that init will work from init.sqf, I have my doubts about it.

Yes, for some reason respawn triggers twice for me in "listen MP" (editor MP preview), I'll check how it works on dedicated. I didn't use init.sqf, I created a bootstrap function with `preinit = 1` (without `recompile`) that called the CBA function for init and respawn.
This can be done "cleanly" in the template as the function remains fully within the feature's scope.

**Comment by freghar** [comment] 2016-03-31 12:33
Also, if we were to go the class-based approach, just imagine how many `Extended_Something_Handlers` would there potentially be - "Something" being each keyword on https://community.bistudio.com/wiki/Arma_3:_Event_Handlers .

**Comment by milivojm** [comment] 2016-03-31 12:35
> Alternatively, you can just leave it there and base further changes on it (I would recommend that approach instead).

I was hoping you're going to say that. I will pay more attention next time.

> Yes, for some reason respawn triggers twice for me in "listen MP" (editor MP preview), I'll check how it works on dedicated. I didn't use init.sqf, I created a bootstrap function with preinit = 1 (without recompile) that called the CBA function for init and respawn.
> This can be done "cleanly" in the template as the function remains fully within the feature's scope.

Maybe you've got `respawnOnStart` set to 0 or 1 in the description.ext? It seems 0 is default value and it does run respawn script.

**Comment by freghar** [comment] 2016-03-31 12:41
> Maybe you've got respawnOnStart set to 0 or 1 in the description.ext? It seems 0 is default value and it does run respawn script.

That should affect only `onPlayerRespawn.sqf`, trying it on dedicated (`respawnOnStart` on its default), it triggers only once. I think we can live with this - it will work even for locally-hosted MP, it just won't be perfectly optimized.

Before going the CBA function fully, I need to test whether it works on editor-placed units - it should according to the execution order, just making sure.

**Comment by freghar** [comment] 2016-03-31 12:59
Works beautifully,
- `init` is triggered when entering the map/briefing screen, so while mission `time` is still 0, which is nice as the loadout can be loaded (hopefully) before players jump into the game
  - as expected, it also runs for curator-spawned, mcc-spawned, etc. units
- `respawn` is triggered once and runs on player units placed in editor

And all I did was https://gist.github.com/freghar/a8e1e7422c145e8471995fdb998b6d77.

Now let me try if I can call a function from the `{}` block without it having `recompile = 1` ...

**Comment by freghar** [comment] 2016-03-31 13:12
Updated the gist, https://gist.github.com/freghar/a8e1e7422c145e8471995fdb998b6d77 , works as expected (as previously), even on a dedicated server, no idea why `recompile` was needed in your case. :(

**Comment by milivojm** [comment] 2016-03-31 13:16
You can have a look if you have too much time - there is a link to testing mission. But it's not that important.

That's great news then. I'll do it soon.

**Comment by freghar** [comment] 2016-03-31 13:28
I just tested JIP and - to my surprise, it works too. Normally, `preInit` isn't executed on JIP, but the CBA function must be adding it to the JIP queue, so it works.

**Comment by milivojm** [comment] 2016-03-31 13:38
I've pushed a new commit to my branch, have a look 8e4c1b329dc08fc49d520972ea27eb71769a46d9

**Comment by freghar** [comment] 2016-03-31 13:45
Looks good, I don't know if you modified it yet, but what should be the location of the `loadouts` dir? I would suggest either
- in `features/Custom_Factions/loadouts/`
- in `userconfig/loadouts/`
  - maybe after feature name? `userconfig/Custom_Factions/` or `userconfig/Custom_Factions/loadouts/`

I would like to have some kind of convention so that people don't have to look at the source code to figure out where it's reading configs from.

**Comment by milivojm** [comment] 2016-03-31 13:49
Let's go with `features/Custom_Factions/loadouts/`.

Should I later add a folder and an example loadout? It's important they manually convert `this` to `_this` on export.

**Comment by freghar** [comment] 2016-03-31 14:00
> Should I later add a folder and an example loadout? It's important they manually convert this to _this on export.

Wouldn't be a bad idea, yes. Something simple and short. I was also thinking where to keep feature-specific documentation, maybe `features/Custom_Factions/README.rst` would be nice - how to use it, to not forget `this` conversion, etc.
See http://docutils.sourceforge.net/docs/user/rst/quickstart.html .

**Comment by milivojm** [comment] 2016-03-31 14:02
Ok. I still have to test this and then I'll do a pull request this time.

**Comment by freghar** [comment] 2016-03-31 15:21
By the way, I think we could pretty safely do `this = _this;` before `execVM`-ing the file, so the user doesn't have to edit the loadout. I _think_ it should be safe as wherever `this` is needed, the engine re-sets it prior to executing said logic.

Might want to test that with multiple units as it might race because both `init = ".."` and unit initialization happen at the same time.

**Comment by milivojm** [comment] 2016-04-01 06:52
Well, I have tried the new code and now it throws errors if script is not there, which was predictable in the first place but somehow didn't appear with XEH. I tried exception handling approach with `try` `catch` but it doesn't do anything, the error still appears and it seems it only catches errors thrown with `throw`. Since the KK script doesn't work on dedicated server, I'm back to square one. Code works, loadout is loaded, but it also throws warnings both on screen (with show scripting errors enabled) and in .rpt. :(

I've tried replacing `execVM` with `preprocessFile` , `loadFile`, `preprocessFileLineNumbers` and compiling them in some private var but the error is still displayed on screen and .rpt.

Killzone Kid mentioned creating a server side extension but I don't think we should go there, it will just ruin the simplicity of this template. Other solutions that I can think of right now are bad from MMs perspective.

**Comment by milivojm** [comment] 2016-04-01 08:46
I will have to force the MM to specify classes in this way:

https://gist.github.com/milivojm/b27a162ab933cbe2887a193e5e847e50

**Comment by freghar** [comment] 2016-04-01 10:09
> I will have to force the MM to specify classes in this way:

You can let the preprocessor help you here and have a single with with

```
"class1",
"class2",
"class3"
```

and

```
...
private _classes = [
#include "thatfile"
];
...
```

Or maybe even use `__FILE__` in a clever way, but that would need putting some line into each loadout file. Or specify a custom `CfgSomething` if it's allowed in `description.txt` and parse that.

No nice solutions, I'm afraid.

**Comment by milivojm** [comment] 2016-04-01 12:12
I think I'd rather go with call as is, `__FILE__` would be cool if you and me are creating the loadouts, but not sure about novice MMs. :)

**Comment by milivojm** [comment] 2016-04-01 13:16
I will try `this = _unit` trick later. It could work though. `this` is a global (I guess) as any other and it seems that if engine itself doesn't step on it's own toes by multiple units racing to reset it's value, then it might be gentle on us too. We'll see. :)

For the future - creating a 3den addon that helps in the process? I think we might have a number of such addons for different things.

**Comment by milivojm** [comment] 2016-04-01 15:16
Ok, this seems to be done, opening a pull request so you can try it. A trick with this doesn't work, possibly because I am using `execVM` for calling a loadout script.

**Comment by freghar** [comment] 2016-04-01 18:20
The global `this` thing doesn't work as `execVM` runs the file in a scheduled environment, returning immediately, so the engine probably re-sets `this` before the `execVM`'d file ever gets a chance to use it.

**Comment by freghar** [comment] 2016-04-02 14:29
After 50 comments, I think we can finally close this, thanks for the cooperation.

**Closed as completed by freghar** 2016-04-02 14:29 UTC
Labels: testing-needed
